-- DEPT 테이블 생성
CREATE table DEPT(
DEPTNO NUMERIC primary key,
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);

-- EMP 테이블 생성
CREATE table EMP(
EMPNO NUMERIC primary key,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMERIC,
HIREDATE DATE,
SAL NUMERIC,
COMM NUMERIC,
DEPTNO NUMERIC,
FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO) 
);


-- VIEW를 이용해서 EMPNO, ENAME, JOB, DNAME 추출
CREATE VIEW EMPLIST AS
SELECT e.EMPNO, e.ENAME, e.JOB, d.DNAME
FROM EMP e, DEPT d
WHERE e.ename = d.dname;


-- transaction 종료
commit;
